### ISSUE TITLE
False Positive - JWT detected in issue quote reply

### ISSUE THREAD

**Issue by vthiery** [octodemo/custom-pattern-secrets#61]
### Pattern Name / Description

We are getting false positived while using the JWT custom pattern `e(?:y[IJ]|yL[CD]|yA[JKgi]|w[ko][JKgi])[A-Za-z0-9_-]{10,}(?:fQ|[3HXn]0|[1BFJNRVZdhlpx]9)={0,2}\.e(?:y[IJ]|yL[CD]|yA[JKgi]|w[ko][JKgi])[A-Za-z0-9_-]{10,}(?:fQ|[3HXn]0|[1BFJNRVZdhlpx]9)={0,2}(?:\.?[A-Za-z0-9_-]+={0,2})?` (from https://github.com/advanced-security/secret-scanning-custom-patterns/tree/main/jwt#readme) in some of our GitHub issues.

The pattern is matched in "quote reply" of comments containing an image. 

### Sample Snippet

![image](https://github.com/advanced-security/secret-scanning-custom-patterns/assets/23509436/8cacabda-6350-44d6-9235-afb38f615e2e)

![image](https://github.com/advanced-security/secret-scanning-custom-patterns/assets/23509436/1e7bccde-4f3f-47b5-876e-23a51a211482)

![image](https://github.com/advanced-security/secret-scanning-custom-patterns/assets/23509436/0e62d6cc-02d7-449c-91c3-bfc682140a6d)

![image](https://github.com/advanced-security/secret-scanning-custom-patterns/assets/23509436/511c5cc1-230f-4dae-897c-45073ea1102c)

This is something I have already quickly mentioned to @aegilops.

Happy to provide further details if needed.

**Comment by GeekMasher** [comment]
Thanks @vthiery, @aegilops and I will take a look next week for you

**Comment by aegilops** [comment]
Ah, this is an interesting one. We do _correctly_ detect a JWT, but the context in which it is detected it is _benign_. It's a GitHub generated JWT to access a private image, and not part of the user-generated content.

I'll see if there's something in the structure of this to help remove it from consideration.

Thanks so much for the report!

**Comment by aegilops** [comment]
Can you try adding this in the custom pattern UI as an additional match that must not match please?

```
^eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.eyJrZXkiOiJrZXkxIiwiZXhwIjo[A-Za-z0-9_-]+(JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9|ZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ|mWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0)\.
```

As in, here:

<img width="1187" alt="Screenshot 2023-06-23 at 18 10 17" src="https://github.com/advanced-security/secret-scanning-custom-patterns/assets/41705651/147e7d98-5ac8-46cc-b0ec-89c38b165a6f">

If you confirm that works for you then I'll put that into the repo.

What that does is match parts of the JWT that are somewhat indicative of this kind of JWT. It'll possibly result in some false negatives, since it isn't _very_ distinctive.

Because of the way that custom patterns work it's not possible for me to make use of the URL content before the JWT in deciding to ignore it - that would be my first choice, to say "ignore if in a URL for `private-user-images.githubusercontent.com/`".

**Comment by vthiery** [comment]
Thanks @aegilops for the quick answer. I just tested your suggestion and it works well for quote replies in issues.
Nevertheless, I got another unwanted match in a quote reply in a pull-request, for which the JWT was missing the signature.
I adjusted the pattern to remove the ending `.` and it now works as expected, i.e. not matching any of the JWT in issue/pr comments.

**Comment by aegilops** [comment]
I'll raise something internally to see if we can make these JWT for this purpose more easily identifiable

**Comment by aegilops** [comment]
We made a change to the JWT format.

The payload of the JWT will always be prefixed with `{"iss":"github.com","aud":"raw.githubusercontent.com",`, which has fixed Base64 of `eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIs`.

You will need to adjust your custom pattern in light of that change, since the previous pattern won't work now.

I'll make a change to the custom pattern YAML file to reflect that.

**Comment by vthiery** [comment]
Thanks @aegilops ! I reconfigured the rule and so far so good :+1:

**Comment by aegilops** [comment]
Fixed now in the pattern with https://github.com/advanced-security/secret-scanning-custom-patterns/pull/88
